/// Generated by AssetsRefGenerator on 2021/12/03
class Res {
  static const String a10_adwaa = "assets/images/adwaa/a10_adwaa.jpg";
  static const String a1_adwaa = "assets/images/adwaa/a1_adwaa.jpg";
  static const String a2_adwaa = "assets/images/adwaa/a2_adwaa.jpg";
  static const String a3_adwaa = "assets/images/adwaa/a3_adwaa.jpg";
  static const String a4_adwaa = "assets/images/adwaa/a4_adwaa.jpg";
  static const String a5_adwaa = "assets/images/adwaa/a5_adwaa.jpg";
  static const String a6_adwaa = "assets/images/adwaa/a6_adwaa.jpg";
  static const String a7_adwaa = "assets/images/adwaa/a7_adwaa.jpg";
  static const String a8_adwaa = "assets/images/adwaa/a8_adwaa.jpg";
  static const String a9_adwaa = "assets/images/adwaa/a9_adwaa.jpg";
  static const String adminLaundry1 =
      "assets/images/adminLaundry/adminLaundry1.PNG";
  static const String adminLaundry2 =
      "assets/images/adminLaundry/adminLaundry2.PNG";
  static const String adminLaundry3 =
      "assets/images/adminLaundry/adminLaundry3.PNG";
  static const String adminLaundry4 =
      "assets/images/adminLaundry/adminLaundry4.PNG";
  static const String adminLaundry5 =
      "assets/images/adminLaundry/adminLaundry5.PNG";
  static const String adminLaundry6 =
      "assets/images/adminLaundry/adminLaundry6.PNG";
  static const String adwaa = "assets/images/adwaa.jpg";
  static const String app_store = "assets/images/app_store.png";
  static const String b10_basha = "assets/images/askELBasha/b10_basha.png";
  static const String b1_basha = "assets/images/askELBasha/b1_basha.png";
  static const String b2_basha = "assets/images/askELBasha/b2_basha.png";
  static const String b3_basha = "assets/images/askELBasha/b3_basha.png";
  static const String b4_basha = "assets/images/askELBasha/b4_basha.png";
  static const String b5_basha = "assets/images/askELBasha/b5_basha.png";
  static const String b6_basha = "assets/images/askELBasha/b6_basha.png";
  static const String b7_basha = "assets/images/askELBasha/b7_basha.png";
  static const String b8_basha = "assets/images/askELBasha/b8_basha.png";
  static const String b9_basha = "assets/images/askELBasha/b9_basha.png";
  static const String blueplanet = "assets/rive/blueplanet.riv";
  static const String d1_driver = "assets/images/graduation/d1_driver.png";
  static const String d2_driver = "assets/images/graduation/d2_driver.png";
  static const String developer = "assets/images/developer.png";
  static const String freelance = "assets/images/freelance.jpg";
  static const String github = "assets/images/github.png";
  static const String house = "assets/rive/house.riv";
  static const String iti = "assets/images/iti.jpg";
  static const String k10_kids = "assets/images/kidsApp/k10_kids.png";
  static const String k11_kids = "assets/images/kidsApp/k11_kids.png";
  static const String k12_kids = "assets/images/kidsApp/k12_kids.png";
  static const String k13_kids = "assets/images/kidsApp/k13_kids.png";
  static const String k1_kids = "assets/images/kidsApp/k1_kids.png";
  static const String k2_kids = "assets/images/kidsApp/k2_kids.png";
  static const String k3_kids = "assets/images/kidsApp/k3_kids.png";
  static const String k4_kids = "assets/images/kidsApp/k4_kids.png";
  static const String k5_kids = "assets/images/kidsApp/k5_kids.png";
  static const String k6_kids = "assets/images/kidsApp/k6_kids.png";
  static const String k7_kids = "assets/images/kidsApp/k7_kids.png";
  static const String k8_kids = "assets/images/kidsApp/k8_kids.png";
  static const String k9_kids = "assets/images/kidsApp/k9_kids.png";
  static const String kidsApp = "assets/images/kidsApp.jpg";
  static const String l10_lawyer = "assets/images/lawyerOffice/l10_lawyer.png";
  static const String l11_lawyer = "assets/images/lawyerOffice/l11_lawyer.png";
  static const String l12_lawyer = "assets/images/lawyerOffice/l12_lawyer.png";
  static const String l13_lawyer = "assets/images/lawyerOffice/l13_lawyer.png";
  static const String l15_lawyer = "assets/images/lawyerOffice/l15_lawyer.png";
  static const String l16_lawyer = "assets/images/lawyerOffice/l16_lawyer.png";
  static const String l17_lawyer = "assets/images/lawyerOffice/l17_lawyer.png";
  static const String l18_lawyer = "assets/images/lawyerOffice/l18_lawyer.png";
  static const String l19_lawyer = "assets/images/lawyerOffice/l19_lawyer.png";
  static const String l1_laundry = "assets/images/laundry/l1_laundry.png";
  static const String l1_lawyer = "assets/images/lawyerOffice/l1_lawyer.png";
  static const String l20_lawyer = "assets/images/lawyerOffice/l20_lawyer.png";
  static const String l2_laundry = "assets/images/laundry/l2_laundry.png";
  static const String l3_laundry = "assets/images/laundry/l3_laundry.png";
  static const String l3_lawyer = "assets/images/lawyerOffice/l3_lawyer.png";
  static const String l4_laundry = "assets/images/laundry/l4_laundry.png";
  static const String l4_lawyer = "assets/images/lawyerOffice/l4_lawyer.png";
  static const String l5_laundry = "assets/images/laundry/l5_laundry.png";
  static const String l5_lawyer = "assets/images/lawyerOffice/l5_lawyer.png";
  static const String l6_laundry = "assets/images/laundry/l6_laundry.png";
  static const String l6_lawyer = "assets/images/lawyerOffice/l6_lawyer.png";
  static const String l7_laundry = "assets/images/laundry/l7_laundry.png";
  static const String l7_lawyer = "assets/images/lawyerOffice/l7_lawyer.png";
  static const String l8_laundry = "assets/images/laundry/l8_laundry.png";
  static const String l8_lawyer = "assets/images/lawyerOffice/l8_lawyer.png";
  static const String l9_laundry = "assets/images/laundry/l9_laundry.png";
  static const String l9_lawyer = "assets/images/lawyerOffice/l9_lawyer.png";
  static const String m10_medi = "assets/images/mediStar/m10_medi.png";
  static const String m11_medi = "assets/images/mediStar/m11_medi.png";
  static const String m12_medi = "assets/images/mediStar/m12_medi.png";
  static const String m13_medi = "assets/images/mediStar/m13_medi.png";
  static const String m1_medi = "assets/images/mediStar/m1_medi.png";
  static const String m2_medi = "assets/images/mediStar/m2_medi.png";
  static const String m3_medi = "assets/images/mediStar/m3_medi.png";
  static const String m4_medi = "assets/images/mediStar/m4_medi.png";
  static const String m5_medi = "assets/images/mediStar/m5_medi.png";
  static const String m6_medi = "assets/images/mediStar/m6_medi.png";
  static const String m7_medi = "assets/images/mediStar/m7_medi.png";
  static const String m8_medi = "assets/images/mediStar/m8_medi.png";
  static const String m9_medi = "assets/images/mediStar/m9_medi.png";
  static const String mediStar = "assets/images/mediStar.jpg";
  static const String nahdet_misr_ai = "assets/images/nahdet_misr_ai.png";
  static const String p1_passenger =
      "assets/images/graduation/p1_passenger.png";
  static const String p2_passenger =
      "assets/images/graduation/p2_passenger.png";
  static const String p3_passenger =
      "assets/images/graduation/p3_passenger.png";
  static const String p4_passenger =
      "assets/images/graduation/p4_passenger.png";
  static const String p5_passenger =
      "assets/images/graduation/p5_passenger.png";
  static const String p6_passenger =
      "assets/images/graduation/p6_passenger.png";
  static const String p7_passenger =
      "assets/images/graduation/p7_passenger.png";
  static const String play = "assets/images/play.png";
  static const String portofolioimage = "assets/images/portofolioimage.PNG";
  static const String tablet_device = "assets/images/tablet_device.png";
  static const String tamimy = "assets/images/tamimy.png";
  static const String Tech_village_Egypt =
      "assets/images/Tech_village_Egypt.jpg";
  static const String tic_1 = "assets/images/ticTacToe/tic_1.png";
  static const String tic_2 = "assets/images/ticTacToe/tic_2.png";
  static const String tic_3 = "assets/images/ticTacToe/tic_3.png";
  static const String tic_4 = "assets/images/ticTacToe/tic_4.png";
  static const String tic_5 = "assets/images/ticTacToe/tic_5.png";
  static const String Tictactoe = "assets/images/Tictactoe.jpg";
  static const String trip_1 = "assets/images/trip/trip_1.png";
  static const String trip_2 = "assets/images/trip/trip_2.png";
  static const String trip_3 = "assets/images/trip/trip_3.png";
  static const String trip_4 = "assets/images/trip/trip_4.png";
  static const String trip_5 = "assets/images/trip/trip_5.png";
  static const String trip_6 = "assets/images/trip/trip_6.png";
  static const String trip_7 = "assets/images/trip/trip_7.png";
  static const String trip_8 = "assets/images/trip/trip_8.png";
  static const String w10_whocaller =
      "assets/images/whoCaller/w10_whocaller.png";
  static const String w11_whocaller =
      "assets/images/whoCaller/w11_whocaller.png";
  static const String w12_whocaller =
      "assets/images/whoCaller/w12_whocaller.png";
  static const String w13_whocaller =
      "assets/images/whoCaller/w13_whocaller.png";
  static const String w1_whocaller = "assets/images/whoCaller/w1_whocaller.png";
  static const String w2_whocaller = "assets/images/whoCaller/w2_whocaller.png";
  static const String w3_whocaller = "assets/images/whoCaller/w3_whocaller.png";
  static const String w4_whocaller = "assets/images/whoCaller/w4_whocaller.png";
  static const String w5_whocaller = "assets/images/whoCaller/w5_whocaller.png";
  static const String w6_whocaller = "assets/images/whoCaller/w6_whocaller.png";
  static const String w7_whocaller = "assets/images/whoCaller/w7_whocaller.png";
  static const String w8_whocaller = "assets/images/whoCaller/w8_whocaller.png";
  static const String w9_whocaller = "assets/images/whoCaller/w9_whocaller.png";
  static const String water_bar_demo = "assets/rive/water_bar_demo.riv";

  //profile images
  static const String ProfileImage = "assets/images/developer.png";
  static const String ProfileImage1 = "assets/images/portofolioimage.PNG";
  static const String ProfileImage2 = "assets/images/tamimy.png";

  //experience images
  static const String NahdetMisrAi = "assets/images/nahdet_misr_ai.png";
  static const String ITI = "assets/images/iti.jpg";
  static const String TechVillageEgypt = "assets/images/Tech_village_Egypt.jpg";
  static const String Freelance = "assets/images/freelance.jpg";

  //projects images
  static const String laundry = "assets/images/laundry.jpg";
  static const String adminLaundry = "assets/images/adminLaundry.jpg";
  static const String CovidTracker = "assets/images/CovidTracker.jpg";
  static const String SafeWay = "assets/images/SafeWay.jpg";
  static const String WhoCaller = "assets/images/WhoCaller.jpg";
  static const String AskELBasha = "assets/images/AskELBasha.jpg";
  static const String LawyerOffice = "assets/images/LawyerOffice.jpg";
  static const String GraduationProject = "assets/images/GraduationProject.jpg";
  static const String ticTacToe = "assets/images/Tictactoe.jpg";

  //rive files
  static const String WaterBarRive = "assets/rive/water_bar_demo.riv";
  static const String BluePlanetRive = "assets/rive/blueplanet.riv";
  static const String HouseRive = "assets/rive/house.riv";

  //project buttons Icon
  static const String GooglePlay = "assets/images/play.png";
  static const String Github = "assets/images/github.png";
  static const String AppStore = "assets/images/app_store.png";
}
